### ISSUE TITLE
Add an E2E test workflow

### ISSUE THREAD

**Issue by bendrucker** [TakeScoop/terraform-cloud-workspace-action#80]
There are [Go integration tests](https://github.com/TakeScoop/terraform-cloud-workspace-action/blob/master/internal/action/main_test.go), but we should also have a full integration test of the Action:

```yml
uses: ./
with:
  terraform_organization: takescoop-oss
```

We could probably be clever here and supply a local backend and then invoke `terraform destroy` in a later step to remove the associated infrastructure
